"use client";
import {useState,useEffect} from "react";
import Link from "next/link";
import {ArrowLeft,Monitor,Download,ShieldCheck,Upload,KeyRound} from "lucide-react";
import {generateAgentKeys} from "@/lib/crypto";
import {Toaster,toast} from "sonner";
type Volume={mountPoint:string;volumeId:string;protection:string;encryptionPercentage:number;encryptionMethod:string;error?:string;protectors:{keyId:string}[]};
type Agent={id:string;name:string;tenant:string;revoked:number;lastSeen:string|null;machineId:string|null;snapshot:string|null};
type Config={version:number;agentId:string;tenant:string;publicKey:string;uploadToken:string;endpoint:null};
function download(config:Config){const url=URL.createObjectURL(new Blob([JSON.stringify(config,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="keyhaven-"+config.agentId+".json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function Agents(){
 const [agents,setAgents]=useState<Agent[]>([]),[busy,setBusy]=useState(false),[config,setConfig]=useState<Config|null>(null),[error,setError]=useState("");
 async function api(data:unknown){const r=await fetch("/api/agents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const j=await r.json() as {error?:string;agents:Agent[];config:Config;accepted:boolean;duplicate?:boolean;stale?:boolean};if(!r.ok)throw Error(j.error||"Agent request failed");return j}
 async function refresh(){const r=await api({action:"list"});setAgents(r.agents)}
 useEffect(()=>{let active=true;fetch("/api/agents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"list"})}).then(async r=>{const j=await r.json() as {agents:Agent[];error?:string};if(!r.ok)throw Error(j.error||"Unable to load agents");if(active)setAgents(j.agents)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setBusy(true);setError("");try{if(data.get("pass")!==data.get("confirm"))throw Error("Passphrases do not match");const keys=await generateAgentKeys(String(data.get("pass")));const r=await api({action:"create",name:data.get("name"),tenant:data.get("tenant"),...keys});setConfig(r.config);form.reset();await refresh();toast.success("Enrollment created. Download its configuration now.")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function importReport(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setError("");try{if(file.size>100000)throw Error("Report exceeds the 100 KB limit");const r=await api({action:"import",report:JSON.parse(await file.text())});toast.success(r.accepted?"Encrypted report imported":r.duplicate?"Report already imported":"Older report ignored");await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false);e.target.value=""}}
 return <main style={{maxWidth:1200}}><Link href="/" className="recover-button" style={{justifyContent:"flex-start",marginBottom:25}}><ArrowLeft size={16}/>Device vault</Link><div className="heading-line"><div><div className="eyebrow">WINDOWS · RMM COLLECTION</div><h1>Collection agents</h1><p>One enrollment per device. Public-key encryption before upload.</p></div><label className="primary" style={{cursor:busy?"wait":"pointer"}}><Upload size={16}/> Import encrypted report<input disabled={busy} type="file" accept=".json" onChange={importReport} style={{display:"block",maxWidth:230,marginTop:8}}/></label></div><div className="security-note" style={{margin:"24px 0"}}><ShieldCheck/>This private pilot supports encrypted file import. Automatic upload requires a separately configured machine-accessible HTTPS endpoint; the private Sites sign-in gate cannot accept RMM bearer credentials.</div>{error&&<p role="alert" style={{color:"#b42318",marginBottom:20}}>{error}</p>}
 <div className="agent-layout"><section className="inventory" style={{padding:24,alignSelf:"start"}}><h2>Enroll a Windows device</h2><p className="muted" style={{marginTop:8}}>The endpoint receives only a public encryption key and an upload-only credential. Retain this enrollment’s passphrase to recover collected keys.</p><form onSubmit={create} className="form-stack"><label>Client tenant<input name="tenant" required maxLength={100}/></label><label>Device label<input name="name" required maxLength={100} placeholder="e.g. Northstar reception PC"/></label><label>Enrollment recovery passphrase<input name="pass" type="password" required minLength={16} autoComplete="new-password"/></label><label>Confirm passphrase<input name="confirm" type="password" required minLength={16} autoComplete="new-password"/></label><button className="primary" disabled={busy||!!config}><KeyRound size={16}/>{busy?"Working…":"Create enrollment"}</button></form>{config&&<div className="security-note form-stack" style={{marginTop:18}}><p>This configuration contains an upload credential. Download it now, store it as an RMM secret file, and deploy it to one device only.</p><button onClick={()=>download(config)}><Download size={16}/>Download configuration</button><button onClick={()=>setConfig(null)}>I saved the configuration</button></div>}</section>
 <section className="inventory"><div className="section-head"><div><h2>Enrolled devices · {agents.length}</h2><p>First accepted report binds enrollment to the Windows machine ID.</p></div><button onClick={()=>refresh().catch(e=>setError(e.message))}>Refresh</button></div>{!agents.length&&<div className="empty"><Monitor/><h3>No devices enrolled</h3><p>Create an enrollment, then deploy the collector through your RMM.</p></div>}{agents.map(a=>{const snapshot=a.snapshot?JSON.parse(a.snapshot) as {hostname:string;os:string;serialNumber:string;collectedAt:string;volumes:Volume[]}:null;return <article key={a.id} style={{borderTop:"1px solid #e2e8ed",padding:22}}><div className="activity" style={{padding:0,border:0}}><Monitor/><div><strong>{a.name}</strong><small>{a.tenant}</small></div><span className="badge">{a.revoked?"Revoked":a.lastSeen?"Reporting":"Awaiting report"}</span>{!a.revoked&&<button disabled={busy} onClick={async()=>{setBusy(true);try{await api({action:"revoke",id:a.id});await refresh();toast.success("Agent revoked")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Revoke</button>}</div><p className="muted" style={{marginTop:12}}>{a.lastSeen?"Last received: "+new Date(a.lastSeen).toLocaleString():"No report received"}{snapshot&&" · Collected: "+new Date(snapshot.collectedAt).toLocaleString()}</p>{snapshot&&<><p style={{marginTop:10,fontSize:14}}>{snapshot.hostname} · {snapshot.os} · Serial: {snapshot.serialNumber||"Unavailable"}</p>{snapshot.volumes.map(v=><div key={v.volumeId} style={{background:"#f5f8f9",padding:12,borderRadius:6,marginTop:10,fontSize:14}}><strong>{v.mountPoint||v.volumeId}</strong><p>Protection {v.protection.toLowerCase()} · {v.encryptionPercentage}% encrypted · {v.encryptionMethod}</p><p className="muted">{v.protectors.length} recovery password protector(s){v.error?" · "+v.error:""}</p></div>)}{!snapshot.volumes.length&&<p className="muted">No BitLocker volumes reported.</p>}</>}</article>})}</section></div><Toaster richColors/></main>
}
