"use client";
import {useState,useEffect} from "react";
import Link from "next/link";
import {ShieldCheck,KeyRound,Building2,Monitor,Link2,History,Search,Plus,ArrowUpRight,LockKeyhole,ChevronRight,SlidersHorizontal,Copy,Eye,Check} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from "@/components/ui/sidebar";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Toaster,toast} from "sonner";
type Share={id:string;name:string;recipient:string;expires:number;used:number;revoked:number}; type Audit={id:string;action:string;detail:string;time:number}; type ApiResponse={error?:string;devices:Device[];shares:Share[];audit:Audit[];cipher:string;token:string;privateKey?:string};
type Device={id:string;tenant:string;name:string;user:string;keyId:string;updated:string;status:string};
const clients=["Northstar Dental","Meridian Financial","Atlas Architecture","Evergreen Health","Summit Legal","Bluebird Creative"];
const demo:Device[]=Array.from({length:124},(_,i)=>({id:"sample-"+i,tenant:clients[i%6],name:["NST-LT","MER-WS","ATL-LT","EVG-WS","SUM-LT","BLU-MB"][i%6]+"-"+String(101+i).padStart(3,"0"),user:["Olivia Martin","James Wilson","Emma Thompson","Noah Williams","Sophia Davis","Liam Anderson"][i%6],keyId:("A"+(483271+i*379).toString(16).toUpperCase()+"B2").slice(0,8),updated:"2026-09-"+String(23-i%5).padStart(2,"0"),status:i%17===0?"Review needed":"Protected"}));
export default function Home(){
const [devices,setDevices]=useState<Device[]>(demo),[sample,setSample]=useState(true),[view,setView]=useState("Device vault"),[query,setQuery]=useState(""),[tenant,setTenant]=useState("all"),[status,setStatus]=useState("all"),[page,setPage]=useState(1),[modal,setModal]=useState(""),[selected,setSelected]=useState<Device|null>(null),[pass,setPass]=useState(""),[vaultPass,setVaultPass]=useState(""),[busy,setBusy]=useState(false),[revealed,setRevealed]=useState(""),[shareUrl,setShareUrl]=useState(""),[shares,setShares]=useState<Share[]>([]),[audit,setAudit]=useState<Audit[]>([]);
useEffect(()=>{
const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
if(!context)return;const lifecycle=new AbortController();
Promise.resolve(context.registerTool({name:"search_device_inventory",description:"Filter the visible device inventory by device, user, client tenant, or recovery key identifier. Does not reveal keys.",inputSchema:{type:"object",properties:{query:{type:"string",maxLength:100}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{const q=(input as {query?:unknown})?.query;if(typeof q!=="string"||q.length>100)throw Error("query must be a string of at most 100 characters");setQuery(q);setPage(1);setTenant("all");setStatus("all");setView("Device vault");return {query:q}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();
},[]);
const [now,setNow]=useState(0); useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
const filtered=devices.filter(d=>(tenant==="all"||d.tenant===tenant)&&(status==="all"||d.status===status)&&[d.name,d.tenant,d.user,d.keyId].join(" ").toLowerCase().includes(query.toLowerCase()));
async function api(action:string,data:Record<string,unknown>={}){const r=await fetch("/api/vault",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...data})});const j=await r.json() as ApiResponse;if(!r.ok)throw Error(j.error||"The vault is unavailable.");return j;}
async function load(){try{const r=await api("list");setDevices(r.devices);setPage(1);setShares(r.shares);setAudit(r.audit);setSample(false);}catch(e){toast.error((e as Error).message)}}
function close(){setModal("");setRevealed("");setShareUrl("");setPass("");}
useEffect(()=>{const timer=setTimeout(()=>{setVaultPass("");setRevealed("");},5*60*1000);return()=>clearTimeout(timer)},[vaultPass]);
useEffect(()=>{const timer=setTimeout(()=>setRevealed(""),60000);return()=>clearTimeout(timer)},[revealed]);

async function reveal(){if(sample){setRevealed("Sample record — no recovery key is stored.");return;}setBusy(true);try{const r=await api("reveal",{id:selected?.id});const {decrypt}=await import("@/lib/crypto");setRevealed(await decrypt(r.cipher,vaultPass||pass,r.privateKey));if(pass)setVaultPass(pass);}catch{toast.error("Unable to unlock. Check your passphrase and try again.");}finally{setBusy(false)}}
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{
const {encrypt,decrypt}=await import("@/lib/crypto");
if(modal==="add"){const key=String(data.key).trim();if(!/^(\d{6}-){7}\d{6}$/.test(key)||key.split("-").some(g=>Number(g)>720885||Number(g)%11!==0))throw Error("Enter a valid 48-digit BitLocker recovery password.");const secret=vaultPass||String(data.pass);if(secret.length<16)throw Error("Use a vault passphrase of at least 16 characters.");await api("add",{tenant:data.tenant,name:data.name,user:data.user,keyId:data.keyId,cipher:await encrypt(key,secret)});setVaultPass(secret);await load();close();toast.success("Recovery key encrypted and saved.");}
if(modal==="share"){if(sample)throw Error("Open your vault and add a real record to create a recovery link.");const r=await api("reveal",{id:selected?.id});const key=await decrypt(r.cipher,vaultPass||String(data.pass),r.privateKey);const secret=String(data.sharePass);if(secret.length<16)throw Error("Use a sharing passphrase of at least 16 characters.");const s=await api("share",{id:selected?.id,recipient:data.recipient,minutes:Number(data.minutes),cipher:await encrypt(key,secret)});setShareUrl(location.origin+"/recover#"+s.token);await load();toast.success("One-use recovery link created.");}
}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
const nav=[{name:"Device vault",icon:KeyRound},{name:"Client tenants",icon:Building2},{name:"Secure shares",icon:Link2},{name:"Audit trail",icon:History}];
return <SidebarProvider><Sidebar className="vault-sidebar"><SidebarHeader><Link className="brand" href="/"><span className="brand-icon"><ShieldCheck size={25}/></span>keyhaven<span className="brand-dot">.</span></Link><div className="workspace"><span className="workspace-mark">IT</span><div><strong>IT Done Right</strong><small>MSP workspace</small></div><ShieldCheck size={16}/></div></SidebarHeader><SidebarContent><p className="nav-label">WORKSPACE</p><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.name}><SidebarMenuButton isActive={view===n.name} onClick={()=>setView(n.name)}><n.icon size={19}/><span>{n.name}</span>{n.name==="Device vault"&&<b className="nav-count">{devices.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><LockKeyhole size={22}/><strong>Every key. In safe hands.</strong><p>Encrypted storage.<br/>Controlled recovery.</p></div></SidebarContent><SidebarFooter><div className="user"><span className="avatar">IT</span><div><strong>Vault administrator</strong><small>Private workspace</small></div></div></SidebarFooter></Sidebar>
<div className="shell"><header className="topbar"><div className="crumb"><SidebarTrigger/>Workspace <ChevronRight size={14}/><strong>{view}</strong></div><div className="top-right"><Link href="/agents" className="recover-button"><Monitor size={15}/> Collection agents</Link><span className="private"><LockKeyhole size={13}/> Private vault</span><span className="avatar small">IT</span></div></header><main><div className="page-heading"><div className="eyebrow">RECOVERY, WITHOUT THE RUNAROUND</div><div className="heading-line"><div><h1>{view}</h1><p>{view==="Device vault"?"Your clients’ recovery keys. One secure place.":view==="Client tenants"?"A clear view of every client under your care.":view==="Secure shares"?"Controlled access, only for as long as it’s needed.":"A record of access and recovery activity."}</p></div><button className="primary" onClick={()=>{setModal("add");setShareUrl("")}}><Plus size={17}/> Add recovery key</button></div></div>
<div className="sample-bar"><span><span className="sample-dot"/>{sample?<><strong>Sample workspace</strong><span>Explore 124 devices across 6 client tenants. No real keys.</span></>:<><strong>Your encrypted vault</strong><span>{vaultPass?"Unlocked for 5 minutes":"Keys are locked"} · Keys never appear in inventory responses.</span></>}</span><button onClick={()=>sample?load():(setVaultPass(""),setRevealed(""),toast.success("Vault locked"))}>{sample?"Open my vault":"Lock vault"} {sample?<ArrowUpRight size={15}/>:<LockKeyhole size={15}/>}</button></div>
<div className="stats"><div><span className="stat-label">Total devices <Monitor/></span><strong>{devices.length.toLocaleString()}</strong><small>Across {new Set(devices.map(d=>d.tenant)).size} client tenants</small></div><div><span className="stat-label">Keys protected <ShieldCheck/></span><strong>{devices.filter(d=>d.status==="Protected").length}</strong><small className="green"><Check size={13}/> {sample?"Sample recovery coverage":"Encrypted in your vault"}</small></div><div><span className="stat-label">Needs attention <KeyRound/></span><strong>{devices.filter(d=>d.status!=="Protected").length}<span className="stat-tag">Review</span></strong><small>Recovery records to verify</small></div><div><span className="stat-label">Active shares <Link2/></span><strong>{shares.filter(s=>!s.used&&!s.revoked&&s.expires>now).length}</strong><small>Time-limited, single-use access</small></div></div>
{view==="Device vault"&&<section className="inventory"><div className="section-head"><div><h2>Recovery key inventory <span>{devices.length}</span></h2><p>Find a device, verify the request, recover with confidence.</p></div><span className="encrypted"><LockKeyhole size={14}/> Keys masked by default</span></div><div className="toolbar"><label className="search"><Search size={18}/><input aria-label="Search devices" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search device, user, or recovery key ID…"/><kbd>/</kbd></label><Select value={tenant} onValueChange={v=>{setTenant(v);setPage(1)}}><SelectTrigger className="filter"><Building2 size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All tenants</SelectItem>{Array.from(new Set(devices.map(d=>d.tenant))).map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={v=>{setStatus(v);setPage(1)}}><SelectTrigger className="filter"><SlidersHorizontal size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="Protected">Protected</SelectItem><SelectItem value="Review needed">Review needed</SelectItem></SelectContent></Select></div>
<Table><TableHeader><TableRow><TableHead>Device / user</TableHead><TableHead>Client tenant</TableHead><TableHead>Recovery key ID</TableHead><TableHead>Status</TableHead><TableHead>Last updated</TableHead><TableHead className="text-right">Recovery</TableHead></TableRow></TableHeader><TableBody>{filtered.slice((page-1)*8,page*8).map(d=><TableRow key={d.id}><TableCell><div className="device-cell"><span className="device-icon"><Monitor size={18}/></span><div><strong>{d.name}</strong><small>{d.user||"Unassigned"}</small></div></div></TableCell><TableCell><span className={"tenant-icon color-"+clients.indexOf(d.tenant)%3}>{d.tenant.slice(0,1)}</span>{d.tenant}</TableCell><TableCell><code>{d.keyId}</code></TableCell><TableCell><span className={d.status==="Protected"?"badge":"badge amber"}>{d.status==="Protected"?<ShieldCheck size={13}/>:<KeyRound size={13}/>} {d.status}</span></TableCell><TableCell className="muted">{d.updated.slice(0,10)}</TableCell><TableCell><button className="recover-button" onClick={()=>{setSelected(d);setModal("recover");setRevealed("")}}>Recover <ChevronRight size={14}/></button></TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<div className="empty"><KeyRound/><h3>{devices.length?"No matching devices":"Your vault is ready for its first key"}</h3><p>{devices.length?"Try another search or client tenant.":"Add a recovery key to begin organizing your client devices."}</p></div>}<div className="table-footer"><span>Showing {filtered.length?((page-1)*8)+1:0}–{Math.min(page*8,filtered.length)} of {filtered.length} devices</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>{page} / {Math.max(1,Math.ceil(filtered.length/8))}</span><button disabled={page*8>=filtered.length} onClick={()=>setPage(page+1)}>Next</button></div></div></section>}
{view==="Client tenants"&&<div className="tenant-grid">{Array.from(new Set(devices.map(d=>d.tenant))).map(t=><button className="tenant-card" key={t} onClick={()=>{setTenant(t);setPage(1);setView("Device vault")}}><span className="tenant-icon">{t[0]}</span><h2>{t}</h2><p>{devices.filter(d=>d.tenant===t).length} devices</p><span>View recovery keys <ArrowUpRight size={16}/></span></button>)}{!devices.length&&<div className="empty">Add a recovery key to create your first client tenant.</div>}</div>}
{view==="Secure shares"&&<section className="inventory"><div className="section-head"><div><h2>Recovery links</h2><p>Recipients need access to this private site and the separate sharing passphrase.</p></div></div>{shares.length?shares.map(s=><div className="activity" key={s.id}><Link2/><div><strong>{s.recipient}</strong><small>{s.name} · Expires {new Date(s.expires).toLocaleString()}</small></div><span className="badge">{s.revoked?"Revoked":s.used?"Opened":s.expires<now?"Expired":"Active"}</span>{!s.revoked&&!s.used&&s.expires>now&&<button onClick={async()=>{try{await api("revoke",{id:s.id});await load();toast.success("Share revoked")}catch(e){toast.error((e as Error).message)}}}>Revoke</button>}</div>):<div className="empty"><Link2/><h3>No recovery links yet</h3><p>Choose a device, then create a time-limited recovery link.</p></div>}</section>}
{view==="Audit trail"&&<section className="inventory"><div className="section-head"><div><h2>Vault activity</h2><p>Key retrieval, storage, and sharing events. Recovery passwords are never logged.</p></div></div>{audit.length?audit.map(a=><div className="activity" key={a.id}><History/><div><strong>{a.action}</strong><small>{a.detail}</small></div><span className="muted">{new Date(a.time).toLocaleString()}</span></div>):<div className="empty"><History/><h3>No activity yet</h3><p>Actions in your vault will appear here.</p></div>}</section>}
<div className="bottom-note"><ShieldCheck size={17}/><span>Built for the moments that matter.</span> Verify the requester before revealing or sharing a recovery key.<span className="bottom-end">KEYHAVEN / MSP</span></div></main></div>
<Dialog open={!!modal} onOpenChange={o=>!o&&close()}><DialogContent className="vault-dialog"><DialogHeader><DialogTitle>{modal==="add"?"Add a recovery key":modal==="share"?"Share recovery access":"Recover device"}</DialogTitle><DialogDescription>{modal==="add"?"Keys are encrypted in your browser before storage. Keep your vault passphrase safe; it cannot be reset.":selected?.name+" · "+selected?.tenant}</DialogDescription></DialogHeader>
{modal==="recover"?<div className="form-stack"><div className="security-note"><LockKeyhole size={20}/>Key access is recorded. Revealed keys hide automatically after 60 seconds.</div>{!vaultPass&&!sample&&<label>Vault passphrase<input type="password" value={pass} onChange={e=>setPass(e.target.value)} autoComplete="off"/></label>}{revealed?<div className="key-box"><code>{revealed}</code>{!sample&&<button onClick={()=>navigator.clipboard.writeText(revealed).then(()=>toast.success("Copied. Clear your clipboard after use."))}><Copy size={16}/>Copy key</button>}</div>:<button className="primary" onClick={reveal} disabled={busy}><Eye size={16}/>{busy?"Unlocking…":"Reveal recovery key"}</button>}<button onClick={()=>{setModal("share");setRevealed("")}}><Link2 size={16}/> Create secure share</button></div>:<form className="form-stack" onSubmit={submit}>{modal==="add"?<><div className="two-col"><label>Client tenant<input name="tenant" required maxLength={100} placeholder="e.g. Northstar Dental"/></label><label>Device name<input name="name" required maxLength={100} placeholder="e.g. NST-LT-101"/></label></div><label>Assigned user<input name="user" maxLength={100} placeholder="Name or email (optional)"/></label><label>Recovery key ID<input name="keyId" required maxLength={80} placeholder="Recovery key identifier"/></label><label>48-digit recovery password<textarea name="key" required placeholder="000000-000000-000000-000000-000000-000000-000000-000000" autoComplete="off"/></label>{!vaultPass&&<label>Vault passphrase<input name="pass" type="password" required minLength={16} autoComplete="new-password" placeholder="At least 16 characters"/></label>}</>:shareUrl?<><div className="security-note">One use only. Send the passphrase through a separate trusted channel. Private-site access is still required.</div><label>Recovery link<input readOnly value={shareUrl}/></label><button type="button" className="primary" onClick={()=>navigator.clipboard.writeText(shareUrl).then(()=>toast.success("Recovery link copied"))}><Copy size={16}/>Copy link</button></>:<><label>Recipient (audit label)<input name="recipient" type="email" required placeholder="requester@client.com"/></label><p className="muted">The recipient label does not restrict access. Anyone with site access, this link, and the passphrase can open it once.</p>{!vaultPass&&<label>Vault passphrase<input name="pass" type="password" required autoComplete="off"/></label>}<label>Separate sharing passphrase<input name="sharePass" type="password" required minLength={16} autoComplete="new-password"/></label><label>Expires in<select name="minutes"><option value="15">15 minutes</option><option value="60">1 hour</option><option value="240">4 hours</option></select></label></>}{!shareUrl&&<button className="primary" disabled={busy}>{busy?"Encrypting…":modal==="add"?"Encrypt & save key":"Create one-use link"}</button>}</form>}</DialogContent></Dialog><Toaster richColors position="bottom-right"/></SidebarProvider>;
}





