import type { LayoutField } from '@atlas/shared';

type Seed = { key: string; name: string; icon: string; description: string; fields: Partial<LayoutField>[] };
const f = (
  key: string,
  label: string,
  type: LayoutField['type'],
  extra: Partial<LayoutField> = {},
): Partial<LayoutField> => ({ key, label, type, ...extra });

// Built-in templates every organization starts with. Admins can edit their fields or add their own layouts.
export const BUILT_IN_LAYOUTS: Seed[] = [
  {
    key: 'configuration',
    name: 'Configurations',
    icon: 'server',
    description: 'Servers, workstations, firewalls, switches, and other devices.',
    fields: [
      f('type', 'Type', 'select', {
        options: [
          'Server',
          'Workstation',
          'Laptop',
          'Firewall',
          'Switch',
          'Access point',
          'Router',
          'Storage',
          'Virtual machine',
          'Hypervisor',
          'Phone',
          'Other',
        ],
        showInList: true,
      }),
      f('hostname', 'Hostname', 'text', { showInList: true }),
      f('ip_address', 'IP address', 'ip', { showInList: true }),
      f('mac_address', 'MAC address', 'text'),
      f('manufacturer', 'Manufacturer', 'text'),
      f('model', 'Model', 'text'),
      f('serial_number', 'Serial number', 'text'),
      f('operating_system', 'Operating system', 'text'),
      f('location', 'Location', 'text'),
      f('management_url', 'Management URL', 'url'),
      f('purchase_date', 'Purchase date', 'date'),
      f('warranty_expires', 'Warranty expires', 'date', { expires: true }),
    ],
  },
  {
    key: 'network',
    name: 'Networks',
    icon: 'network',
    description: 'Subnets and VLANs with their gateways and DHCP scopes.',
    fields: [
      f('subnet', 'Subnet', 'ip', { required: true, showInList: true, help: 'For example 10.20.0.0/24' }),
      f('vlan', 'VLAN ID', 'number', { showInList: true }),
      f('gateway', 'Gateway', 'ip'),
      f('dns_servers', 'DNS servers', 'text'),
      f('dhcp_range', 'DHCP range', 'text'),
      f('purpose', 'Purpose', 'select', {
        options: ['Data', 'Voice', 'Guest', 'Management', 'Servers', 'IoT', 'Other'],
        showInList: true,
      }),
      f('location', 'Location', 'text'),
    ],
  },
  {
    key: 'domain',
    name: 'Domains',
    icon: 'globe',
    description: 'Registered domains, their registrar, and DNS host.',
    fields: [
      f('registrar', 'Registrar', 'text', { showInList: true }),
      f('dns_host', 'DNS host', 'text'),
      f('expires', 'Expires', 'date', { expires: true, showInList: true }),
      f('auto_renew', 'Auto-renew', 'checkbox'),
      f('nameservers', 'Name servers', 'textarea'),
    ],
  },
  {
    key: 'ssl_certificate',
    name: 'SSL certificates',
    icon: 'shield-check',
    description: 'Certificates, where they are installed, and when they expire.',
    fields: [
      f('common_name', 'Common name', 'text', { required: true, showInList: true }),
      f('issuer', 'Issuer', 'text', { showInList: true }),
      f('expires', 'Expires', 'date', { expires: true, showInList: true }),
      f('subject_alt_names', 'Subject alternative names', 'textarea'),
      f('installed_on', 'Installed on', 'text'),
    ],
  },
  {
    key: 'license',
    name: 'Licenses',
    icon: 'badge-check',
    description: 'Software subscriptions and license keys (keys move to the vault in M2).',
    fields: [
      f('product', 'Product', 'text', { required: true, showInList: true }),
      f('vendor', 'Vendor', 'text'),
      f('seats', 'Seats', 'number', { showInList: true }),
      f('renewal_date', 'Renewal date', 'date', { expires: true, showInList: true }),
      f('billing', 'Billing', 'select', { options: ['Monthly', 'Annual', 'Perpetual', 'Other'] }),
    ],
  },
  {
    key: 'application',
    name: 'Applications',
    icon: 'app-window',
    description: 'Line-of-business applications, their vendors, and support details.',
    fields: [
      f('vendor', 'Vendor', 'text', { showInList: true }),
      f('version', 'Version', 'text', { showInList: true }),
      f('hosting', 'Hosting', 'select', { options: ['On premises', 'Cloud (SaaS)', 'Hybrid'] }),
      f('url', 'URL', 'url'),
      f('support_contact', 'Vendor support', 'text'),
      f('business_owner', 'Business owner', 'text'),
    ],
  },
  {
    key: 'backup',
    name: 'Backups',
    icon: 'hard-drive-download',
    description: 'What is backed up, where, how often, and how it is tested.',
    fields: [
      f('product', 'Product', 'text', { showInList: true }),
      f('scope', 'What is protected', 'textarea'),
      f('schedule', 'Schedule', 'text', { showInList: true }),
      f('retention', 'Retention', 'text'),
      f('destination', 'Destination', 'text'),
      f('last_restore_test', 'Last restore test', 'date'),
    ],
  },
  {
    key: 'email',
    name: 'Email',
    icon: 'mail',
    description: 'Mail platform, domains, and mail flow.',
    fields: [
      f('platform', 'Platform', 'select', {
        options: ['Microsoft 365', 'Google Workspace', 'Exchange on premises', 'Other'],
        showInList: true,
      }),
      f('tenant', 'Tenant or domain', 'text', { showInList: true }),
      f('mx_records', 'MX records', 'textarea'),
      f('filtering', 'Filtering service', 'text'),
      f('spf_dkim_dmarc', 'SPF / DKIM / DMARC notes', 'textarea'),
    ],
  },
  {
    key: 'internet',
    name: 'Internet / WAN',
    icon: 'router',
    description: 'Circuits, carriers, and static addressing.',
    fields: [
      f('provider', 'Provider', 'text', { required: true, showInList: true }),
      f('circuit_id', 'Circuit ID', 'text'),
      f('bandwidth', 'Bandwidth', 'text', { showInList: true }),
      f('static_ips', 'Static IPs', 'textarea'),
      f('support_phone', 'Support phone', 'phone'),
      f('account_number', 'Account number', 'text'),
      f('location', 'Location', 'text'),
    ],
  },
  {
    key: 'wireless',
    name: 'Wireless',
    icon: 'wifi',
    description: 'SSIDs and how they are secured (passphrases move to the vault in M2).',
    fields: [
      f('ssid', 'SSID', 'text', { required: true, showInList: true }),
      f('security', 'Security', 'select', {
        options: ['WPA3 Enterprise', 'WPA3 Personal', 'WPA2 Enterprise', 'WPA2 Personal', 'Open'],
        showInList: true,
      }),
      f('vlan', 'VLAN', 'number'),
      f('guest', 'Guest network', 'checkbox'),
      f('controller', 'Controller', 'text'),
    ],
  },
  {
    key: 'printer',
    name: 'Printers',
    icon: 'printer',
    description: 'Printers and multifunction devices.',
    fields: [
      f('model', 'Model', 'text', { showInList: true }),
      f('ip_address', 'IP address', 'ip', { showInList: true }),
      f('location', 'Location', 'text'),
      f('driver', 'Driver', 'text'),
      f('supplies_vendor', 'Supplies vendor', 'text'),
    ],
  },
  {
    key: 'vendor',
    name: 'Vendors',
    icon: 'handshake',
    description: 'Third parties the client relies on, and how to reach them.',
    fields: [
      f('service', 'Service', 'text', { showInList: true }),
      f('account_number', 'Account number', 'text'),
      f('support_phone', 'Support phone', 'phone', { showInList: true }),
      f('support_email', 'Support email', 'email'),
      f('portal', 'Portal', 'url'),
      f('contract_ends', 'Contract ends', 'date', { expires: true }),
    ],
  },
  {
    key: 'remote_access',
    name: 'Remote access',
    icon: 'monitor-smartphone',
    description: 'VPNs, remote desktop gateways, and remote support tools.',
    fields: [
      f('method', 'Method', 'select', {
        options: ['VPN', 'Remote desktop gateway', 'Remote support tool', 'Bastion host', 'Other'],
        showInList: true,
      }),
      f('address', 'Address', 'text', { showInList: true }),
      f('authentication', 'Authentication', 'text'),
      f('allowed_users', 'Who may use it', 'textarea'),
    ],
  },
];

export const withDefaults = (field: Partial<LayoutField>): LayoutField => ({
  key: field.key!,
  label: field.label!,
  type: field.type!,
  required: field.required ?? false,
  options: field.options ?? [],
  help: field.help ?? '',
  showInList: field.showInList ?? false,
  expires: field.expires ?? false,
});
